Added Chinese translation, README.cn.md for issue #36
Lorenalgm/DevChallenge pull request #46
Opened 2020-11-01 03:17 UTC by NickCwh

2020-11-01 16:04 UTC, esau-morais requested changes
Thank you for contributing to the Chinese language!!

_Note: See the requested changes to be approved_
_Note 2: See again the template to make it's all good_

2020-11-01 16:04 UTC, esau-morais commented on README.cn.md
> +- [Índice](#índice)
Once you change the heading name, you need to change the link too

_Note: To test if it works see [this extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) to preview_

2020-11-06 18:11 UTC, magdielndantas approved these changes

2020-12-15 02:36 UTC, Lorenalgm commented
Thanks for the translation, Nick!

2020-12-15 02:37 UTC, merged